# Project information
site_name: Foxy Docs
site_description: Foxy Documentation
site_author: felixbrucker
site_url: https://docs.foxypool.cf

# Repository
repo_name: foxy-docs
repo_url: https://github.com/felixbrucker/foxy-docs

# Theme
theme:
  name: 'material'
  favicon: assets/img/favicon.ico
  feature:
    - tabs
  palette:
    primary: indigo
    accent: indigo

# Options
extra:
  manifest: 'manifest.webmanifest'
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/felixbrucker

# Page tree
nav:
  - General:
      - Home: index.md
      - Installing Nodejs: installing-nodejs.md
      - Donate: donate.md
  - Foxy-Pool:
      - Home: foxy-pool/index.md
      - Mining: foxy-pool/mining.md
      - Binding:
          - AETH: foxy-pool/binding/aeth.md
          - BHD: foxy-pool/binding/bhd.md
          - BURST: foxy-pool/binding/burst.md
          - HDD: foxy-pool/binding/hdd.md
          - LHD: foxy-pool/binding/lhd.md
          - XHD: foxy-pool/binding/xhd.md
      - Pledging: foxy-pool/pledging.md
      - Settings: foxy-pool/settings.md
      - Distribution Ratio: foxy-pool/distribution-ratio.md
      - API:
          - Overview: foxy-pool/api/overview.md
          - Web-UI API: foxy-pool/api/web-ui-api.md
          - Mining API: foxy-pool/api/mining-api.md
  - Foxy-Miner:
      - Home: foxy-miner/index.md
      - Installing: foxy-miner/installing.md
      - Configuration: foxy-miner/configuration.md
  - Foxy-Proxy:
      - Home: foxy-proxy/index.md
      - Installing: foxy-proxy/installing.md
      - Configuration: foxy-proxy/configuration.md
  - Pledge-Agent:
      - Home: pledge-agent/index.md
      - Supported coins: pledge-agent/supported-coins.md
      - Installing: pledge-agent/installing.md
      - Configuration: pledge-agent/configuration.md


# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - minify:
      minify_html: true