---
###############################################################################################
##                             ARCHON DEFAULT CONFIGURATION FILE                             ##
###############################################################################################
## For help and guidance, see the github readme at https://github.com/Bloodreaver/Archon     ##
## You can also join the Discord at https://discord.gg/ZdVbrMn if you need further help! :)  ##
###############################################################################################

# Grace Period: How long (in seconds) Archon will let blocks mine for before considering them to be completed.
# NOTE: This value is extremely important, it is used as a timer by Archon to determine how much time must elapse after a block starts
#   before Archon can send the next queued block to be mined. Set it too small, and Archon will instruct your miners to start mining a 
#   new block before they've finished scanning the previous one. Conversely, set it too long, and you risk missing blocks entirely.
#   Ideally it should be set around 5 seconds longer than your regular scan times, 5 seconds just to give it a safety net.
gracePeriod: 20

# Priority Mode: Optional. Default: True.
#   TRUE: Chains will be mined in the order specified in the chain configurations below.
#  FALSE: Blocks will be mined on a first in, first out basis.
priorityMode: true

# Interrupt Lower Priority Blocks: Optional. Default: True. Only used in priority mode.
#   TRUE: Lower priority blocks will be interrupted by new blocks from a higher priority chain.
#  FALSE: Blocks will not be interrupted unless outdated by a new block from the same chain.
interruptLowerPriorityBlocks: true

# Web Server Bind Address: Which interface to listen for requests from your miners and/or web requests.

# Localhost only - will only listen for requests made from the same machine
#webServerBindAddress: 127.0.0.1

# LAN IP - Will listen for requests made over your local network to this machine, if this machines LAN IP = 192.168.1.1
# NOTE: This probably isn't your machine's LAN IP, you'll need to change it!
#webServerBindAddress: 192.168.1.1

# Universal - bind to all interfaces
webServerBindAddress: 0.0.0.0

# Web Server Port: Listen for requests on this port.
webServerPort: 1337

# Use PoC Chain Colors: Optional. Default: True. Whether to use colors in console logging for each chain.
# NOTE: On windows, if your colors are dim, see: https://blogs.msdn.microsoft.com/commandline/2017/08/02/updating-the-windows-console-colors/
usePocChainColors: true

# Show Human Readable Deadlines: Optional. If true, values displayed in seconds will be appended with a human readable value, for example: 3345951 (1m 8d 17:25:51)
showHumanReadableDeadlines: true

# Logging Level: Optional. Default: Info. Case insensitive.
#   Valid options: off|trace|debug|info|warn|error
loggingLevel: info

# Show Miner Addresses: Optional. Default: false.
#   Shows the IP Address of miner's which submit deadlines.
showMinerAddresses: false

######################################################################################################################
# Define PoC Chains to mine here, Archon will exit if there are no chains configured/enabled, you need at least one! #
######################################################################################################################

######## See https://github.com/Bloodreaver/Archon#defining-your-mining-chains for help with this if needed ########

pocChains:
  # BHD via Foxy Pool
  - name: BHD - FoxyPool
    url: "https://bhd.foxypool.cf"
    priority: 0
    color: yellow
    payoutAddress: "your BHD payout address"
    minerAlias: "your desired name"
    minerName: "your desired miner name"
    appendVersionToMinerName: true
    isBhd: true
    isPool: true
  # BTB via Foxy Pool
  - name: BTB - FoxyPool
    url: "https://btb.foxypool.cf"
    priority: 1
    color: magenta
    payoutAddress: "your BTB payout address"
    minerAlias: "your desired name"
    minerName: "your desired miner name"
    appendVersionToMinerName: true
    isPool: true
  # BURST via Foxy Pool
  - name: BURST - FoxyPool
    url: "https://burst.foxypool.cf"
    priority: 2
    color: blue
    payoutAddress: "your BURST payout address"
    minerAlias: "your desired name"
    minerName: "your desired miner name"
    appendVersionToMinerName: true
    isPool: true
